language: python
python:
    - "2.7"

sudo: false
cache:
    directories:
        - "~/.platformio"

install:
    - pip install -U platformio
    - pip install cpplint
    - pip install cppclean
    - platformio update

script:
    - platformio run
    - cpplint src/*.cpp
    - cppclean src/*.cpp
