language: python
python:
    - "2.7"

sudo: false
cache:
    directories:
        - "~/.platformio"

install:
    - pip install -U platformio
    - pip install cpplint
    - sudo apt-get install cppcheck
    - platformio update

script:
    - platformio run
    - cpplint src/*.cpp
    - cppcheck --enable=style src/*.cpp
